Controllers/AlbumController.cs
using Musique.Data;
using Musique.Models;
using Microsoft.AspNetCore.Mvc;

namespace Musique.Controllers;

public class AlbumController : Controller
{
    private readonly DataContext _db;

    public AlbumController(DataContext db)
    {
        _db = db;
    }

    public IActionResult Index()
    {
        var albuns = _db.Albuns.ToList();
        return View(albuns);
    }

    [HttpGet]
    public IActionResult Create()
    {
        var album = new Album();
        return View(album);
    }
    [HttpPost]
    public IActionResult Create(Album album)
    {
        if(!ModelState.IsValid) return View(album);
        _db.Albuns.Add(album);
        _db.SaveChanges();
        return RedirectToAction("Index");
    }
    [HttpGet]
    public IActionResult Edit(int id)
    {
        var album = _db.Albuns.Find(id);
        if(album is null)
            return RedirectToAction("Index");
        return View(album);
    }
    [HttpPost]
    public IActionResult Edit(int id, Album album)
    {
        var originalalbum = _db.Albuns.Find(id);
        if(originalalbum is null)
           return RedirectToAction("Index");
        if(!ModelState.IsValid){
            return View(album);
        }            
        
        originalalbum.Nome = album.Nome;     
        originalalbum.DataLancamento = album.DataLancamento;     
        _db.SaveChanges();
        return RedirectToAction("Index");
    }
    [HttpGet]
    public IActionResult Delete(int id)
    {
        var album = _db.Albuns.Find(id);
        if(album is null)
            return RedirectToAction("Index");
        return View(album);
    }
    [HttpPost]
    public IActionResult ProcessDelete(int IdAlbum)
    {
        var album = _db.Albuns.Find(IdAlbum);
        if(album is null)
            return RedirectToAction("Index");
        _db.Albuns.Remove(album);
        _db.SaveChanges();
        return RedirectToAction("Index");
    }

}

Controllers/ArtistaController.cs
using Musique.Data;
using Musique.Models;
using Microsoft.AspNetCore.Mvc;

namespace Musique.Controllers;

public class ArtistaController : Controller
{
    private readonly DataContext _db;

    public ArtistaController(DataContext db)
    {
        _db = db;
    }

    public IActionResult Index()
    {
        var artistas = _db.Artistas.ToList();
        return View(artistas);
    }
    [HttpGet]
    public IActionResult Create()
    {
        var artista = new Artista();
        return View(artista);
    }
    [HttpPost]
    public IActionResult Create(Artista artista)
    {
        if(!ModelState.IsValid) return View(artista);
        _db.Artistas.Add(artista);
        _db.SaveChanges();
        return RedirectToAction("Index");
    }
    [HttpGet]
    public IActionResult Edit(int id)
    {
        var artista = _db.Artistas.Find(id);
        if(artista is null)
            return RedirectToAction("Index");
        return View(artista);
    }
    [HttpPost]
    public IActionResult Edit(int id, Artista artista)
    {
        var artistaoriginal = _db.Artistas.Find(id);
        if(artistaoriginal is null)
            return RedirectToAction("Index");
        if(!ModelState.IsValid)
            return View(artista);

        artistaoriginal.Nome = artista.Nome;
        artistaoriginal.Email = artista.Email;
        artistaoriginal.Senha = artista.Senha;
        artistaoriginal.Telefone = artista.Telefone;
        artistaoriginal.Biografia = artista.Biografia;
        _db.SaveChanges();
        return RedirectToAction("Index");
    }
}

Controllers/GeneroController.cs
using Musique.Data;
using Musique.Models;
using Microsoft.AspNetCore.Mvc;

namespace Musique.Controllers;

public class GeneroController : Controller
{
    private readonly DataContext _db;

    public GeneroController(DataContext db)
    {
        _db = db;
    }
    [HttpGet]
    public IActionResult Create()
    {
        var genero = new Genero();
        return View(genero);
    }
    [HttpPost]
    public IActionResult Create(Genero genero)
    {
        if(!ModelState.IsValid) return View(genero);
        _db.Generos.Add(genero);
        _db.SaveChanges();
        return RedirectToAction("Index");
    }

    public IActionResult Index()
    {
        var generos = _db.Generos.ToList();
        return View(generos);
    }
    [HttpGet]
    public IActionResult Edit(int id)
    {
        var genero = _db.Generos.Find(id);
        if(genero is null)
            return RedirectToAction("Index");
        return View(genero);
    }
    [HttpPost]
    public IActionResult Edit(int id, Genero genero)
    {
        var generooriginal = _db.Generos.Find(id);
        if(generooriginal is null)
            return RedirectToAction("Index");
        if(!ModelState.IsValid)
            return View(genero);

        generooriginal.Nome = genero.Nome;
        _db.SaveChanges();
        return RedirectToAction("Index");
    }
}

Controllers/MusicaController.cs
using Musique.Data;
using Musique.Models;
using Microsoft.AspNetCore.Mvc;

namespace Musique.Controllers;

public class MusicaController : Controller
{
    private readonly DataContext _db;

    public MusicaController(DataContext db)
    {
        _db = db;
    }

    public IActionResult Index()
    {
        var musicas = _db.Musicas.ToList();
        return View(musicas);
    }
    [HttpGet]
    public IActionResult Create()
    {
        var musica = new Musica();
        return View(musica);
    }
    [HttpPost]
    public IActionResult Create(Musica musica)
    {
        if(!ModelState.IsValid) return View(musica);
        _db.Musicas.Add(musica);
        _db.SaveChanges();
        return RedirectToAction("Index");
    }

    [HttpGet]
    public IActionResult Edit(int id)
    {
        var musica = _db.Musicas.Find(id);
        if(musica is null)
            return RedirectToAction("Index");
        return View(musica);
    }
    [HttpPost]
    public IActionResult Edit(int id, Musica musica)
    {
        var originalmusica = _db.Musicas.Find(id);
        if(originalmusica is null)
           return RedirectToAction("Index");
        if(!ModelState.IsValid){
            return View(musica);
        }            
        
        originalmusica.Nome = musica.Nome;
        originalmusica.Letra = musica.Letra;        
        _db.SaveChanges();
        return RedirectToAction("Index");
    }

    [HttpGet]
    public IActionResult Delete(int id)
    {
        var musica = _db.Musicas.Find(id);
        if(musica is null)
            return RedirectToAction("Index");
        return View(musica);
    }
    [HttpPost]
    public IActionResult ProcessDelete(int IdMusica)
    {
        var musica = _db.Musicas.Find(IdMusica);
        if(musica is null)
            return RedirectToAction("Index");
        _db.Musicas.Remove(musica);
        _db.SaveChanges();
        return RedirectToAction("Index");
    }

}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="pt-br">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
    <link rel="stylesheet" href="~/css/teste.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.9.1/font/bootstrap-icons.css">
    <title>Document</title>
</head>

<body>
    <nav>
        <div class="container py-3 mb-4">
            <div class="row d-md-none">
                <div class="col-12 text-center mb-2"><a asp-action="Index" asp-controller="Home"><img src="~/img/musique_logo.png" class="logo-header"></a></div>
                <div class="col-12 text-center">
                    <ul class="list-unstyled">
                        <li class="d-inline"><a asp-action="Index" asp-controller="Home" class="josisney text-decoration-none">Home</a></li>
                        <li class="d-inline"><a asp-action="Index" asp-controller="Genero" class="josisney text-decoration-none">Gêneros</a></li>
                        <li class="d-inline"><a asp-action="Index" asp-controller="Artista" class="josisney text-decoration-none">Artistas</a></li>
                        <li class="d-inline"><a asp-action="Index" asp-controller="Album" class="josisney text-decoration-none">Albuns</a></li>
                        <li class="d-inline"><a asp-action="Index" asp-controller="Sugestao" class="josisney text-decoration-none">Sugestões</a></li>
                    </ul>
                </div>
            </div>
            <div class="row align-items-center">
                <div class="col-2 d-none d-md-block"><a asp-action="Index" asp-controller="Home"><img src="~/img/musique_logo.png" class="logo-header"></a></div>
                <div class="col-3 col-lg-4 d-none d-md-block text-center">
                    <ul class="list-unstyled align-items-center my-1">
                        <li class="d-inline"><a asp-action="Index" asp-controller="Home" class="josisney text-decoration-none">Home</a></li>
                        <li class="d-inline"><a asp-action="Index" asp-controller="Genero" class="josisney text-decoration-none">Gêneros</a></li>
                        <li class="d-inline"><a asp-action="Index" asp-controller="Artista" class="josisney text-decoration-none">Artistas</a></li>
                        <li class="d-inline"><a asp-action="Index" asp-controller="Album" class="josisney text-decoration-none">Albuns</a></li>
                        <li class="d-inline"><a asp-action="Index" asp-controller="Sugestao" class="josisney text-decoration-none">Sugestões</a></li>
                    </ul>
                </div>
                <div class="col-7 col-md-5 col-lg-4">
                    <form class="d-flex justify-content-center">
                        <input class="form-control me-2 shadow-none" type="search" placeholder="Pesquisar"
                            aria-label="Pesquisar">
                        <button class="btn botao" type="submit"><i class="bi bi-search"></i></button>
                    </form>
                </div>
                <div class="col-5 col-md-2">
                    <div class="nav-item dropdown text-end">
                        <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown"
                            aria-expanded="false">
                            Usuário
                        </a>
                        <ul class="dropdown-menu">
                            <li><a class="dropdown-item" asp-action="Create" asp-controller="Ouvinte">Registro</a></li>
                            <li><a class="dropdown-item" asp-action="Index" asp-controller="Musica">Musicas</a></li>
                            <li><a class="dropdown-item" asp-action="Index" asp-controller="Gravacao">Gravações</a></li>
                            <li><a class="dropdown-item" asp-action="Index" asp-controller="Ouvinte">Ouvintes</a></li>
                            <li><a class="dropdown-item" asp-action="Index" asp-controller="Sugestao">Sugestões</a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </nav>
    <div class="container">
        @RenderBody()
    </div>


    <footer class="py-3 mt-4 bg-dark">
        <ul class="nav justify-content-center border-bottom pb-3 mb-3">
            <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">Features</a></li>
            <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">FAQs</a></li>
            <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">Sobre</a></li>
        </ul>
        <p class="text-center text-muted">© 2022 Company, Inc</p>
    </footer>


    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-u1OknCvxWvY5kfmNBILK2hRnQC3Pr17a+RTT6rIHI7NnikvbZlHgTPOOmMi466C8"
        crossorigin="anonymous"></script>
</body>

</html>

Views/Shared/_LayoutHero.cshtml
<!DOCTYPE html>
<html lang="pt-br">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
    <link rel="stylesheet" href="~/css/teste.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.9.1/font/bootstrap-icons.css">
    <title>Document</title>
</head>

<body>
    <nav>
        <div class="container py-3 mb-4">
            <div class="row d-md-none">
                <div class="col-12 text-center mb-2"><a asp-action="Index" asp-controller="Home"><img src="~/img/musique_logo.png" class="logo-header"></a></div>
                <div class="col-12 text-center">
                    <ul class="list-unstyled">
                        <li class="d-inline"><a asp-action="Index" asp-controller="Home" class="josisney text-decoration-none">Home</a></li>
                        <li class="d-inline"><a asp-action="Index" asp-controller="Genero" class="josisney text-decoration-none">Gêneros</a></li>
                        <li class="d-inline"><a asp-action="Index" asp-controller="Artista" class="josisney text-decoration-none">Artistas</a></li>
                        <li class="d-inline"><a asp-action="Index" asp-controller="Album" class="josisney text-decoration-none">Albuns</a></li>
                        <li class="d-inline"><a asp-action="Index" asp-controller="Sugestao" class="josisney text-decoration-none">Sugestões</a></li>
                    </ul>
                </div>
            </div>
            <div class="row align-items-center">
                <div class="col-2 d-none d-md-block"><a asp-action="Index" asp-controller="Home"><img src="~/img/musique_logo.png" class="logo-header"></a></div>
                <div class="col-3 col-lg-4 d-none d-md-block text-center">
                    <ul class="list-unstyled align-items-center my-1">
                        <li class="d-inline"><a asp-action="Index" asp-controller="Home" class="josisney text-decoration-none">Home</a></li>
                        <li class="d-inline"><a asp-action="Index" asp-controller="Genero" class="josisney text-decoration-none">Gêneros</a></li>
                        <li class="d-inline"><a asp-action="Index" asp-controller="Artista" class="josisney text-decoration-none">Artistas</a></li>
                        <li class="d-inline"><a asp-action="Index" asp-controller="Album" class="josisney text-decoration-none">Albuns</a></li>
                        <li class="d-inline"><a asp-action="Index" asp-controller="Sugestao" class="josisney text-decoration-none">Sugestões</a></li>
                    </ul>
                </div>
                <div class="col-7 col-md-5 col-lg-4">
                    <form class="d-flex justify-content-center">
                        <input class="form-control me-2 shadow-none" type="search" placeholder="Pesquisar"
                            aria-label="Pesquisar">
                        <button class="btn botao" type="submit"><i class="bi bi-search"></i></button>
                    </form>
                </div>
                <div class="col-5 col-md-2">
                    <div class="nav-item dropdown text-end">
                        <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown"
                            aria-expanded="false">
                            Usuário
                        </a>
                        <ul class="dropdown-menu">
                            <li><a class="dropdown-item" asp-action="Create" asp-controller="Ouvinte">Registro</a></li>
                            <li><a class="dropdown-item" asp-action="Index" asp-controller="Musica">Musicas</a></li>
                            <li><a class="dropdown-item" asp-action="Index" asp-controller="Gravacao">Gravações</a></li>
                            <li><a class="dropdown-item" asp-action="Index" asp-controller="Ouvinte">Ouvintes</a></li>
                            <li><a class="dropdown-item" asp-action="Index" asp-controller="Sugestao">Sugestões</a></li>
                            
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </nav>
    <div class="container-fluid">
        @RenderBody()
    <footer id="footer" class="footer">

        <div class="container">
            <div class="row gy-4">
                <div class="col-lg-5 col-md-12 footer-info">
                    <a href="index.html" class="logo d-flex align-items-center">
                        <span>Musique</span>
                    </a>
                    <p>Nos acompanhe nas nossas redes sociais!</p>
                    <div class="social-links d-flex mt-4">
                        <a href="#" class="twitter"><i class="bi bi-twitter"></i></a>
                        <a href="#" class="facebook"><i class="bi bi-facebook"></i></a>
                        <a href="#" class="instagram"><i class="bi bi-instagram"></i></a>
                    </div>
                </div>

                <div class="col-lg-2 col-6 footer-links">
                    <h4>Links Importantes</h4>
                    <ul>
                        <li><a href="#">Home</a></li>
                        <li><a href="#">Sobre Nós</a></li>
                        <li><a href="#">Services</a></li>
                        <li><a href="#">Privacy policy</a></li>
                    </ul>
                </div>

                <div class="col-lg-3 col-md-12 footer-contact text-center text-md-start">
                    <h4>Nos Contate</h4>
                    <p>
                        Instituto Federal do Espírito Santo <br>
                        Campus Cachoeiro de Itapemirim<br>
                        Espírito Santo <br><br>
                        <strong>Telefones:</strong> (28) 99955-1216; (28) 99914-4550; (28) 99946-7316<br>
                        <strong>Emails:</strong> giselleasv@gmail.com; izas212@gmail.com; mellpinon29@gmail.com<br>
                    </p>

                </div>

            </div>
        </div>

        <div class="container mt-4">
            <div class="copyright">
                &copy; Copyright <strong><span>Musique</span></strong>. All Rights Reserved
            </div>
        </div>

    </footer><!-- End Footer -->

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-u1OknCvxWvY5kfmNBILK2hRnQC3Pr17a+RTT6rIHI7NnikvbZlHgTPOOmMi466C8"
        crossorigin="anonymous"></script>
</body>

</html>