Models/Gravacao.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Musique.Models;

public class Gravacao
{

    [Key]
    public int IdGravacao { get; set; }

    public DateTime DataLancamento { get; set; }

    public double Duracao { get; set; }

    [ForeignKey("Artista")]
    public int IdArtista { get; set; }
    public Artista Artista { get; set; }

    [ForeignKey("Genero")]
    public int IdGenero { get; set; }
    public Genero Genero { get; set; }

    [ForeignKey("Musica")]
    public int IdMusica { get; set; }
    public Musica Musica { get; set; }

    [ForeignKey("Album")]
    public int IdAlbum { get; set; }
    public Album Album { get; set; }

    public ICollection<Avaliacao> Avaliacoes { get; set; }
}

Controllers/GravacaoController.cs
using Musique.Data;
using Musique.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace Musique.Controllers;

public class GravacaoController : Controller
{
    private readonly DataContext _db;

    public GravacaoController(DataContext db)
    {
        _db = db;
    }

    private void LoadGeneros(int? idSelectedGenero = null)
    {
        var generos = _db.Generos.ToList();
        var selectGeneros = new SelectList(generos, "IdGenero", "Nome", idSelectedGenero);
        ViewBag.SelectGeneros = selectGeneros;
    }
    private void LoadAlbuns(int? idSelectedAlbum = null)
    {
        var generos = _db.Albuns.ToList();
        var selectAlbuns = new SelectList(generos, "IdAlbum", "Nome", idSelectedAlbum);
        ViewBag.SelectAlbuns = selectAlbuns;
    }
    private void LoadArtistas(int? idSelectedArtista = null)
    {
        var artistas = _db.Artistas.ToList();
        var selectArtistas = new SelectList(artistas, "IdUsuario", "Nome", idSelectedArtista);
        ViewBag.SelectArtistas = selectArtistas;
    }
    private void LoadMusicas(int? idSelectedMusica = null)
    {
        var musicas = _db.Musicas.ToList();
        var selectMusicas = new SelectList(musicas, "IdMusica", "Nome", idSelectedMusica);
        ViewBag.SelectMusicas = selectMusicas;
    }

    public IActionResult Index()
    {
        var gravacoes = _db.Gravacoes.Include(a=>a.Artista).Include(a=>a.Musica).ToList();
        return View(gravacoes);
    }
    public IActionResult Details(int IdGravacao)
    {
        var gravacao = _db.Gravacoes.FirstOrDefault(gr => gr.IdGravacao == IdGravacao);
        return View(gravacao);
    }
    [HttpGet]
    public IActionResult Create()
    {
        LoadArtistas();
        LoadGeneros();
        LoadMusicas();
        LoadAlbuns();
        var gravacao = new Gravacao();
        return View(gravacao);
    }
    [HttpPost]
    public IActionResult Create(Gravacao gravacao)
    {
        if(!ModelState.IsValid){
            LoadArtistas(gravacao.IdArtista);
            LoadGeneros(gravacao.IdGenero);
            LoadMusicas(gravacao.IdMusica);
            LoadAlbuns(gravacao.IdAlbum);
            return View(gravacao);
        } 
        _db.Gravacoes.Add(gravacao);
        _db.SaveChanges();
        return RedirectToAction("Index");
    }
    [HttpGet]
    public IActionResult Edit(int id)
    {
        var gravacao = _db.Gravacoes.Find(id);
        if(gravacao is null)
            return RedirectToAction("Index");
        LoadArtistas(gravacao.IdArtista);
        LoadGeneros(gravacao.IdGenero);
        LoadMusicas(gravacao.IdMusica);
        LoadAlbuns(gravacao.IdAlbum);
        return View(gravacao);
    }
    [HttpPost]
    public IActionResult Edit(int id, Gravacao gravacao)
    {
        var gravacaooriginal = _db.Gravacoes.Find(id);
        if(gravacaooriginal is null)
            return RedirectToAction("Index");
        if(!ModelState.IsValid){
            LoadArtistas(gravacao.IdArtista);
            LoadGeneros(gravacao.IdGenero);
            LoadMusicas(gravacao.IdMusica);
            LoadAlbuns(gravacao.IdAlbum);
            return View(gravacao);
        }
        gravacaooriginal.IdAlbum = gravacao.IdAlbum;
        gravacaooriginal.IdArtista = gravacao.IdArtista;
        gravacaooriginal.DataLancamento = gravacao.DataLancamento;
        gravacaooriginal.Duracao = gravacao.Duracao;
        gravacaooriginal.IdGenero = gravacao.IdGenero;
        gravacaooriginal.IdMusica = gravacao.IdMusica;
        _db.SaveChanges();
        return RedirectToAction("Index");
    }
    [HttpGet]
    public IActionResult Delete(int id)
    {
        var gravacao = _db.Gravacoes.Find(id);
        if(gravacao is null)
            return RedirectToAction("Index");
        return View(gravacao);
    }
    [HttpPost]
    public IActionResult ProcessDelete(int IdGravacao)
    {
        var gravacao = _db.Gravacoes.Find(IdGravacao);
        if(gravacao is null)
            return RedirectToAction("Index");
        _db.Gravacoes.Remove(gravacao);
        _db.SaveChanges();
        return RedirectToAction("Index");
    }

}

Views/Gravacao/Create.cshtml
@model Gravacao;
<div class="col-6 col-xl-4 offset-3 offset-xl-4 text-center">
    <form method="POST">
        <h1>Cadastro - Música</h1>
        <hr class="mb-4">
        <div class="row">
            <div class="form-floating col-11 mb-3 col-11">
                <input type="date" class="form-control" asp-for="@Model.DataLancamento" placeholder="Nome">
                <label asp-for="@Model.DataLancamento" class="ms-3">Data de Lançamento</label>
            </div>
            <div class="col-1"><i class="bi bi-question-circle" id="datalancamento" onclick="detalhes(this)"></i></div>

            <div class="form-floating col-11 mb-3">
                <input type="number" class="form-control" asp-for="@Model.Duracao" placeholder="Nome">
                <label asp-for="@Model.DataLancamento" class="ms-3">Duração</label>
            </div>
            <div class="col-1"><i class="bi bi-question-circle" id="duracao" onclick="detalhes(this)"></i></div>
            

            <div class="form-floating col-11 mb-3">
                <select class="form-select" asp-for="@Model.IdArtista" asp-items="@ViewBag.SelectArtistas">
                    <option value="" selected>Artista</option>
                </select>
            </div>
            <div class="col-1"><i class="bi bi-question-circle" id="artista" onclick="detalhes(this)"></i></div>
            

            <div class="mb-3 col-11">
                <select class="form-select" asp-for="@Model.IdGenero" asp-items="@ViewBag.SelectGeneros">
                    <option value="" selected>Gênero</option>
                </select>
            </div>
            <div class="col-1"><i class="bi bi-question-circle" id="genero" onclick="detalhes(this)"></i></div>
            

            <div class="mb-3 col-11">
                <select class="form-select" asp-for="@Model.IdMusica" asp-items="@ViewBag.SelectMusicas">
                    <option value="" selected>Musica</option>
                </select>
            </div>
            <div class="col-1"><i class="bi bi-question-circle" id="musica" onclick="detalhes(this)"></i></div>
            

            <div class="mb-3 col-11">
                <select class="form-select" asp-for="@Model.IdAlbum" asp-items="@ViewBag.SelectAlbuns">
                    <option value="" selected>Album</option>
                </select>
            </div>
            <div class="col-1"><i class="bi bi-question-circle" id="album" onclick="detalhes(this)"></i></div>
            
        </div>

        <button class="btn botao my-3" type="submit">Cadastrar</button>
    </form>
</div>

<script src="~/js/detalhes.js" defer></script>

Views/Gravacao/Delete.cshtml
@model Gravacao

<h2>Deletando Gravação</i></h2>
<h3>Tem Certeza que deseja deletar essa gravação?
</h3>
<hr>

<form method="POST" asp-action="ProcessDelete">
    <a asp-action="Index" asp-controller="Gravacao" class="btn btn-success">Não</a>
    <input type="hidden" asp-for="@Model.IdGravacao">
    <button type="submit" class="btn btn-danger">Sim</button>
</form>

Views/Gravacao/Edit.cshtml
@model Gravacao;
<div class="col-6 col-xl-4 offset-3 offset-xl-4 text-center">
            <form method="POST">
                <h1>Cadastro - Música</h1>
                <hr class="mb-4">
                <div class="form-floating mb-3">
                    <input type="date" class="form-control" asp-for="@Model.DataLancamento" placeholder="Nome">
                    <label asp-for="@Model.DataLancamento">Data de Lançamento</label>
                </div>
                <div class="form-floating mb-3">
                    <input type="number" class="form-control" asp-for="@Model.Duracao" placeholder="Nome">
                    <label asp-for="@Model.DataLancamento">Duração</label>
                </div>

                <div class="form-floating mb-3">
                    <select class="form-select" asp-for="@Model.IdArtista" asp-items="@ViewBag.SelectArtistas">
                        <option value="" selected>Artista</option>
                    </select>
                </div>

                <div class="mb-3">
                    <select class="form-select" asp-for="@Model.IdGenero" asp-items="@ViewBag.SelectGeneros">
                        <option value="" selected>Gênero</option>
                    </select>
                </div>

                <div class="mb-3">
                    <select class="form-select" asp-for="@Model.IdMusica" asp-items="@ViewBag.SelectMusicas">
                        <option value="" selected>Musica</option>
                    </select>
                </div>

                <select class="form-select" asp-for="@Model.IdAlbum" asp-items="@ViewBag.SelectAlbuns">
                        <option value="" selected>Album</option>
                    </select>
                <button class="btn botao my-3" type="submit">Salvar</button>
            </form>
        </div>

Views/Gravacao/Index.cshtml
@model List<Gravacao>;
    <h1 class="text-center mb-3">Gravações Cadastradas</h1>

    <div class="text-center"><a asp-action="Create" class="btn botao text-center mb-3">Cadastrar nova gravação</a></div>

<table class="table table-dark table-striped">
    <th scope="col">Artista</th>
    <th scope="col">Nome</th>
    <th scope="col">Lançamento</th>
    <th scope="col">Duração</th>
    <th scope="col">Detalhes</th>
    <th scope="col">Delete</th>
    </tr>
    </thead>
    <tbody>
        @foreach (var gravacao in Model)
        {
            <tr>
            <th scope="row">@gravacao.Artista.Nome</th>
            <th>@gravacao.Musica.Nome</th>
            <td>@gravacao.DataLancamento</td>
            <td>@gravacao.Duracao</td>
            <td><a asp-action="Edit" asp-controller="Gravacao" asp-route-id="@gravacao.IdGravacao">Editar</a></td>
            <td><a asp-action="Delete" asp-controller="Gravacao" asp-route-id="@gravacao.IdGravacao">Excluir</a></td>
            </tr>
        }
    </tbody>
</table>